---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "cd server && docker build -t axw-digital/insight-node ."
      - "cd server && docker tag axw-digital/insight-node 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoiU1dsVTdiUC9UQVB0VGExa0VtQVVYRWlobllPQ1U0clBSblA2bDZ6clJhbnVWcUoyZVluVmdKTXZ6bFFLWjF3empsUTI3OG1zREpRdm9abzFPWFZ1T01GUWc1dUZUT1NzNzVTZGkxSEFUUTNmRnlQa2lVYmlYYnRtWEdUYStxa1RPZ3NMdlBOVC9hUE4zNkxPa2hSdis3RDFhNTdHdTVQNXlQMUV0ZkRNSUIvcUMwOGx1UUZvcjkyVWMvdUt5d3cvSzJ2MmVPdkhMeVIxb0hKQnNaS0tCZHBzWGo3S1hrYnZveEcwTjNJN1NvaGpxSmpMcldMWFkvV1grdEpTSU9DbHRQRldrVlhUam91aGxKdjNMU1RVQnptY2pkMXRYaVBDUUE3SjB0L2lXcHlEaUlCdWtuczc5VVRIYzFESTE5TkM5b1BXcElHVUtnYzBza294aGo2blRhNU56a3NCbVRkVXJnbnRiZ1I5aXdWQjR3a21tdGVXWXEvWXpFT09vYTBBQWVRZ1g0TmdnNHMzdHpDVHlVN3p6cldoTnFoVnlqRzlRbHBhWndRVStXT3k5R1FiSFoxaG0wcWtjeHp3cHZLcjlCZURkaWZPaGozWTdQNEZPckdnU1BDVFdEMmo3c0VsazBxVEtuOFZVRmlrWDJaK0xVVlY3STBPWkpYMzIwcWo3eWRHLzVjRXRXdG9BOVlaMzdzdGxBMnZmVVBpK3Q0N2RsVG1uK2dmaDFLcitOV0hQUFJvMlo2ZHhsZEVrUTNLRlJTSTJ6eTM5YlFiRUo2Mk9oTnZJMVMzUFFDRXpYVWxjL3l3ejRTY3NtWUpXS1VaL0NqcDcrbHBFRGJLbVVuWnRUNVF6VWtIN2s2VnBJYmtONU5ZOUhNMUxseDNxS0VaZzBDb1pZcGp6WEpYQ21sY3M0NU1uYmEyOVdBMVR6K2NVWmh2SDFUMUFrVGMwZmY4bHRva0V3bHZWN21xVTdjRnlXNU5vMktweStJVVpndWxlOGwxNXVFbDk2YlRWRGIySi9qYUhaRDMxODE3U215ZXBhQjRZVXNoc2VnaXJaN3IxaWtIelh6eU1MV0JGc1JyUVJNRXZ5S1JRYWM1TVQ1VGdlcTlyYWhsd2VVbEJLUzVxREM0RHhjeWFNUDZBS1Ywc2pYbjk1K0J3M1NwUHVSc1FRMkRwdVk1bisvSVJ3anNjbVp1NHRHK053SHBLNk9kMWFDMGVKL0g3eEE4YngrSnBIbldCTDNUWUhVWW82L2dUZWhxYU4zNCtpNmhOVjVka3pEeEhKTFY4S2E1QmNIOWtTRFk2dk9uaXBSTmZNNG9mSG02MGxDK3MzemgiLCJkYXRha2V5IjoiQVFJQkFIaGZyRlEyYUlJd0Y1VmM3OVJIRVBHbmNVV3VyMi9Kek04dC9aem9FdFJyQWdHWE8wTmhrdHpWY3JBVlFVN1lGSVVMQUFBQWZqQjhCZ2txaGtpRzl3MEJCd2FnYnpCdEFnRUFNR2dHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNMkI3VjhOQ25yQlpWemFkTUFnRVFnRHM0VUxoUXVrV0E0OFhJaEVlMmpFNTBET0dmdmNFbWo4STJsL2VLallQOWdPUUVuRHIrYkZGOVlpQllmblhucTA0TXRidVpTZXpBSjVmVm5RPT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2NDQ5MDA2NTl9 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1
