---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "cd server && docker build -t axw-digital/insight-node ."
      - "cd server && docker tag axw-digital/insight-node 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoiM1V6Q25ZQXA4WWJGNVNwYkNoR3lLLy9Qd0ZWeGRNdTk0Nlk0UFF4NzZIOXAzS0JUTHhKOEgwOHI2dkE1eE5XVGZTcnBPSmx2WmlEYkxTcHBvTE1nU0JVNkgxRHB1WGxFSjByc2lSUWt2emZOSk1tTC9aUGJOK0VrQWVLK24yTXB4WmNKQVZLeGpqVXMxeENZRUNyZzFCS0xJbGhqbDc2Z2hpREcyZHJ3N0dYSnZkeWp6dGFDdzlsU04xN0F5dEdQaDhzRExpSmJjcnRIeFlQY2c2UnFETlFYRHh3RWJNRDkrci96eXMvanY4c1IvNTRMaElPWE4vVENFVHF3RXF2b3h5czRvc04wQzlwbzQvYlBQT2hlMjMyZ2UvMnJxQVhmbnhiZkhRRktPWTZHaTFVN2RFZzdpQkovNVJ1S0Vkd1RFNzVDN0ovNVE3YXppNzJ1Nm9ycW1MZ1NGUUY3Tmd0MXJNV3FSVENxWGtuOFN2ZFpwRXExcTBRYXByL3dodTdUR2swMDc2YW9ZTGJKTTVwWGxRQlZ2QnVZV0M3M3NSSFhESE9GUWZMK1ZlRC81N0FkZkRHQk1EZVJ4eU9icE1NYWJDeHlsWlZXTkxRa2RZbDcyRmZRZS9lZWJHU3lMcVdnMzl5WG0zZzVCZ1c1TTZoUWVkRGtjTXJLK3FWQlhiYWlaVnE5c0Q1NEJUUVdqalNxN1pmeGVsWEdqS0Y0Y0hmVDBxWmMzKzdLenI0RS9oYlo5aVNSYks0aGpYeWtQY25GMzJlS3ZOZlhZbEVrUW1idUtxU0tJdlloa0swNktWQmhjVjFFZG9KQk9aRmV3dTlXNDFKYmtUUE1Da0N3QlFrREtLYlVCd1dwbVM4OEd6VS9WbDAyTi9pdWpHUnp3bWJNR3NxandnL1dUbUd3ZWE3dkluNm5FMFE0eXVrNXJTVjQ5S2xqZngwNVErWlE5cVBVRmJxbFJ1cVJjalkvSTFSTnlmbTRXakY0STRRSHIxVGxraHNra2JORjM5ajI0MGhRbFhWNmNzUU9tcHdKd0cwUzltdXpBcHRoM1AxaXN3VHg0U0grS2NOYlExVkpTQzJ5NXZLYVRFS0tWeTlNbzRZalNMK2d5VlNHOEN0WUdlMmNtdW44bHFNaEE4WkV0TmxHTVV2cHlNR3RtaUY2bll6UVRGcjVEVGh3QTBTS3hKU2hyYm9tZmw1RGQ1VUJMVm9NYVZTb0ZSOS9obzBJZkpRVXNMcW9QTmViOE9BNXR3bDVralVKRTZqRHFhQklBWDNjZm84eTVlWlUwWEtYU3Vtd2NiRkR5MjJiaTJQTCtpdGJCK25ueDdpSHAraC9weERBRCtlb0grMWZrMDB4IiwiZGF0YWtleSI6IkFRSUJBSGhmckZRMmFJSXdGNVZjNzlSSEVQR25jVVd1cjIvSnpNOHQvWnpvRXRSckFnSEtWdmltc1Fjakc4SjVFd3VyYkp3UkFBQUFmakI4QmdrcWhraUc5dzBCQndhZ2J6QnRBZ0VBTUdnR0NTcUdTSWIzRFFFSEFUQWVCZ2xnaGtnQlpRTUVBUzR3RVFRTTRadkFLZGR3YWthTTA4THhBZ0VRZ0R1QWhWdko0azV4QnNFVFEzNURrZmUyTGRqdUFFRjJkUnlRaTRtZnBka3E5MUh4MlBlYzFBK2d2bXpld2YvbnRVNTdhTFJUbjErSXIzaTVyQT09IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNjQ5MTI3MzIyfQ== 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1
