---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "cd server && docker build -t axw-digital/insight-node ."
      - "cd server && docker tag axw-digital/insight-node 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoiT2NWR1FQWlNCbFdSUm5iT0pRb2kwb1JvVEZDVHdUWUZJVzdMa1c1WWp3WUlLZ0p6U2IyWUs4Ync2bTZreWJ4bzBFNkxIT3BMdFNhaHVBd3hHSjFWRktwREh3Z0lzUnZScmFtd0pSaHlMQk5lR0V0bGYyYXkyT2hCVjdBeFFMRU9GOVpTalAyNzh6aHQ0ZWYyQ3dOZjhaTnpJK3YvVnBxT1FqUmVHLzdIVUQzSE9ub0xuZE1ac0xlVmRDdllaVGYxQWNaQ1hrWGVtOTNOSGtrMmowVUdIUmFoWisyVmw4ZXY4cE0rRVNqOXBtSXJMQ3BLK09rTnZYdjBYTXd0T1JWWDFUTnlnaVpRL1dJakh0WWtVaVJ4cHgxNG9keEFOTzlvY2ZrSGttampBdDJxb0E2a2JLT1lGUUJmd3E5N2VEL01IUTJMTXZycUVhWlU5NVZtUXVWNURJQmdOSWpVZGZZeWdMVWhyV1ZNamFkL0JkYU8rRXhDNmdXTU5DR0o4RE9JaWN5c2NualkwU1krbTJLWkVHOXNBYU5PbnEwaW5NYTY1L0dqNUtadk5RTm12NjB1WFh0dHFqMlZwZ3pjWmdrVmlFODQreVIxS015UmpYZmtaNGwwRWJpOEh5K3FUOUF1VS80cTZrTkNteTVmMzBMZVhyODVQQytDN3ByaWpkaHg3U3ZUVnF1MExqdjJpMmVMRENsSG1Td1Q4aU9yL0l5VjRDNUprSFVQY29UaWxrb1Q3TXAxbnNFWlZFTmU3WDdJNVJEZ0VZM0NTSmwxZlc0M01DSVdmVWpwRHh2VVpGUkoxYzRjN1RYQ3ovcGE1NjJIU0pVMTZadzZqS2RDR213eE9TSS83RUpka1BxYWIrQkhiNi8vZUs5eUtpdVgyWWVxc21qWHF4RExaRFJZMnpzc0gvSW1BajdpVHpkcnpqQ2xIdTAyTXE5RzFjaEJIeGxCMk5RdWJnbnFGZE4vRzNrVTA5MXB5M1VuRmppRGIzYUcxYXh4ZzRHMVZvaElKazJiM20wN1U4V2JFTmVRMFlmemF5NHMxc1VkNXdiR2RzN0t3NU5XY2pmTjZudVIvR1BMbWhjRllFaStDYlFoUjBqOFJKZFJNRDhDN3NLQWNZWkpZMTRvLzdxUmkzb29VcmNaU25iV2diK01RT25wclVZVDF6VXJuemU5ZkV1bDErVGc1My9JUmQrRWltemtxaU1pZDBlNUpxZ2l3cUw1NnIyVUNEVnJVT25CaE8zZXN2ZTdlVG9nZDRwVzJnUDIvTjUxajlXV0NDbVRVQTJZQVFvTytjNnpPc080KzhiNXZSR1JHTGhJWUhDa3YwdDUiLCJkYXRha2V5IjoiQVFJQkFIaGZyRlEyYUlJd0Y1VmM3OVJIRVBHbmNVV3VyMi9Kek04dC9aem9FdFJyQWdIaU85eTYraFRjUzFLMmtaM1pWU1lJQUFBQWZqQjhCZ2txaGtpRzl3MEJCd2FnYnpCdEFnRUFNR2dHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNdGMyQk9HeHlsQytJc1JjUEFnRVFnRHUrRWl4c1JwOGd6cUQ2eTBDOFpqTE9ud2pvbG9yVGY0WExNM3c0NCtsRWU4S3pRWWR3UEhYV3AvejlTOTB4NjhlbFNYWjVNRlNOQkdFTXJBPT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2NDAwNjU2NTN9 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1
