---
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "cd server && docker build -t axw-digital/insight-node ."
      - "cd server && docker tag axw-digital/insight-node 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 740126133497.dkr.ecr.eu-north-1.amazonaws.com/insight_front"
  pre_build: 
    commands: 
      - "echo Logging in to AWS..."
      - "docker login -u AWS -p eyJwYXlsb2FkIjoiTTRWa0ZvZFBmQjRPVVU4dVRpdHhWa08zN2FJQi9mQ3o3amhYNFk1em9zbmpQbUJuaVVaTDYzSi9mbll5MEsrZGwybW1PdWZ0azZNVUdFaW1HWGZ2ZzlBc09RT2NlMWlPMU9RSlRBUDl1emp6UXpwbzc1U0lpS0dqekovOFcrQjRYVDYvYVlIWHlUN0tUM2l0YTdqcWluRTl5b2NWbFR6aEdrQTVlcVRLWWxQQzFXWGw2K0RucDhMRGFaL2o0ZXQvcitCNzFNTHNCTTJ3NlBlcFArQktmV1BSenp0MHh2dUVRZDkwZ3F0N0R4NFVYc1cxakhRbW1Reng4QWFZWU1idFovcWNKdkJNZFRUQ3VWc2FhU1VsaFF0VkVybEdPcDloTlJ1aHhRVmxlaktzZFFEd2pmU3ZlanpwcWViRHZnSjkxRjVoZGMzTzJYQU5vTW5vcVl2OEovcEZyaHp4OURrci9mWlYzNTFrckFFRW9zMFNnVGFBNVZGeEptZ3hMUU5xU3oyenBlRUZTRGRpcEhBd3pZYmdhUGR2dGN1MnhZWUl3THRvTWVweDBDYzIyL1V5cHJNVnNIVUlKUXovdmFuYlNSRlFaWDI3U2lxNDNPcFB2ODdkeG8xUXdwY2VrZkZhWVpPZE9VSVRaSi9TT0U2K1FNS3RPMnRFeTluVVVOdXF5Wk9TbnptL25pVFJCRytqbUR5b0cwditMZ2NIbWdIbGdZY2pscEsxNDc0d3hMYlNXOG9MM1U4YnNhQ3NhQ2pjRVlYOTRRMUU0dEI1cm1xV3hsbU5MNkZENGJKdUZCMEVETFJmR3hVekhWRXIvK01tbG90enNJem4yKzBYV1RtTnA4UUVjZDVoN3Bvc0NySkZLb1dpQnd2cXM3TUszZ0h5YlBIRTBWM0NUc3MzTkVHWWFaVkxMb01LYjc2RnJkOEloaUpHemd5WjM3SkdrWHdSdktndnZCUTRTSGdBeUREV2ZmQ2llRGNVRlR0V1hLVlp1YWRqNVNXbDdHdUlEWTRsWlhoZjhHVmJ4MXBzME1Eb015SGlLeEdIbisrcllXUm1TbFNEcWN4SHRseWZEd0REMkdFc0x6OGtRWkFCbm13eTJ1enlSV0FzVWs2b1RqUDd2RkV4cTJwSkVDV0pjWFNHNmRlaDQ2NGtaN3l1UjErRnEwZ2t3b1dOQlhJczJaK1k3alhIMENoNnBEY3pVaTJZMGlJdHE3d1FEUVYwemVzKzR2VFVWamw3U1hRREY5WmpMOCtTdjJzZm0zMDRmVXZNVGlESmVaUEpuSUpkYWJETitxQ2xvb3pSR0p3NG5iOW5RNStLOUp6RkVENjUrNHJJd3Z3TnllMWZuN2hORStGaERzZnFuZTVOWlhaRmZXZG9RZTAvUlJ3PSIsImRhdGFrZXkiOiJBUUlCQUhoZnJGUTJhSUl3RjVWYzc5UkhFUEduY1VXdXIyL0p6TTh0L1p6b0V0UnJBZ0ZCK2svc1BlUUZnbFIrcE9kcHJQRU5BQUFBZmpCOEJna3Foa2lHOXcwQkJ3YWdiekJ0QWdFQU1HZ0dDU3FHU0liM0RRRUhBVEFlQmdsZ2hrZ0JaUU1FQVM0d0VRUU1vWm9YMmlTZUNYNForZVh2QWdFUWdEczQ2SEZaVWlqL3RPNHVWQzVwaXNGSnl0WFNxK3BsL2pUT3FLL1Vnc2tnUUdXb3VxZ0VNTXNmSGZVWmJrYVRZcjMyTFNhNmFySEt1aU05ZXc9PSIsInZlcnNpb24iOiIyIiwidHlwZSI6IkRBVEFfS0VZIiwiZXhwaXJhdGlvbiI6MTYzMTgxNTA5OH0= 740126133497.dkr.ecr.eu-north-1.amazonaws.com"
artifacts:
  files: 
    - "**/*"
  name: "s3-to-s3-latest-build.zip" 
version: 0.1
