import React from 'react';
import terms from '../assets/js/termsAndConditions';


class TermsAndConditionsPage extends React.Component {
    render() {
        return (
            <div>
                <section className="d-flex align-items-center odd-section">
                    <div className="container">
                        <div className="row">
                            <div>
                                <h1>Käyttehdot</h1>
                                <h2 id="1-soveltamisala" class="heading-xl hyphenate pb-3 pt-6">1. Soveltamisala</h2>
                                <p class="pb-3 body-text">Näitä käyttöehtoja (jäljempänä ”Käyttöehdot”) sovelletaan Growflow Oy:n tai sen tytäryhtiöiden (jäljempänä ”Growflow”) tuottamiin ja ylläpitämiin maksullisiin ja maksuttomiin sisältöpalveluihin (jäljempänä ”Palvelu”).</p>
                                <p class="pb-3 body-text">Palveluita ovat esimerkiksi
                                    <a href="/" class="link underline">&nbsp; vaikuttava.io – verkkopalvelu</a>
                                    ,
                                    <a href="https://cannurgun.wixsite.com/website-3" class="link underline">&nbsp; Canin verkkokauppa &nbsp;</a>
                                    sekä Growflown verkkokaupat ja mobiilipalvelut. Käyttöehtoja sovelletaan Palveluiden käyttämiseen.
                                </p>
                                <p class="pb-3 body-text">Palvelua käyttävä henkilö (jäljempänä ”Asiakas”) vakuuttaa tutustuneensa Käyttöehtoihin ja sitoutuu kaikilta osin noudattamaan niitä sekä muita mahdollisia Palveluun liittyviä ja niiden yhteydessä erikseen ilmeneviä rajoituksia, ehtoja tai ohjeita sekä Growflown tietosuojalauseketta (”Erityisehdot”). Mikäli nämä Käyttöehdot ja Erityisehdot ovat ristiriidassa, sovelletaan siltä osin ensisijaisesti Erityisehtoja.</p>
                                <h2 id="2-palvelun-kaytt" class="heading-xl hyphenate pb-3 pt-6">2. Palvelun käyttö</h2>
                                <p class="pb-3 body-text">Asiakas saa Palveluun näiden Käyttöehtojen ja mahdollisten Erityisehtojen mukaisen rajoitetun käyttöoikeuden. Asiakas vastaanottaa Palvelun ja käyttää sitä omalla vastuullaan. Palvelua tulee käyttää ehtojen sekä sovellettavien lakien ja muiden säädösten mukaisesti</p>
                                <p class="pb-3 body-text">Palvelut voivat olla osaksi maksullisia. Palvelun käyttö voi edellyttää voimassa olevaa tilausta ja/tai siihen liittyvää
                                    <a href="/profile" class="link underline">&nbsp; Growflow-tiliä</a>
                                </p>
                                <p class="pb-3 body-text">Maksullisten Palveluiden hinnat ja maksuehdot on ilmoitettu niiden yhteydessä. Palveluiden joidenkin osioiden käyttö voi edellyttää Asiakkaan kirjautumista. Asiakas ei saa purkaa tai ohittaa Growflown Palvelun luvattoman käytön ehkäisemiseksi mahdollisesti tekemiä suojauksia tai mittareita.</p>
                                <p class="pb-3 body-text">Palvelun käyttö edellyttää soveltuvaa selainta, sovellusta tai muuta yhteyden muodostamiseen tarvittavaa tietoliikenneohjelmaa sekä asianmukaisia tietoliikenneyhteyksiä, joista aiheutuvat kustannukset maksaa Asiakas. Palvelun toimittaminen ja käyttö edellyttää, että Asiakas on huolehtinut laitteidensa ja muiden Asiakkaan vastuulle kuuluvien seikkojen asennuksesta ja toimivuudesta - ja ettei muu tässä sopimuksessa mainittu syy (kuten esimerkiksi kolmannesta osapuolesta johtuva syy) estä Palvelun toimittamista tai käyttöönottoa.</p>
                                <p class="pb-3 body-text">Asiakas ei saa yhdistää tai käyttää Palvelua siten, että siitä aiheutuu kohtuutonta kuormitusta tai muuta haittaa verkolle, muille Asiakkaille, kolmansille osapuolille tai Growflowlle. Palvelua ei mm. saa käyttää roskapostin tai muun luvattoman tietoliikenteen välittämiseen taikka Growflown tai muun tahon edustajana esiintymiseen oikeudetta. Palvelua ei saa käsitellä tavalla, jolla pyritään peittämään Palvelun kautta välitetyn sisällön alkuperä. Palvelua tai sen sisältöä ei saa käyttää lainvastaisen tai joitakin tuotteita tai palveluja oikeudettomasti mainostavan aineiston julkaisemiseen tai välittämiseen, muiden käyttäjien henkilötietojen oikeudettomaan keräämisen tai tallentamiseen taikka muuhun lainvastaiseen toimintaan. Growflowlla on oikeus vedota kaikkiin näiden ehtojen rikkomisesta johtuviin laillisiin oikeuksiinsa.</p>
                                <p class="pb-3 body-text">Growflow voi antaa erikseen tarkempia ohjeita verkkoa kuormittavasta ja kielletystä käytöstä. Mikäli Palvelussa on käyttöraja, voi Palvelua käyttää sen mukaisesti. Käyttörajojen kiertäminen tai toiminnan estäminen on kiellettyä.</p>
                                <p class="pb-3 body-text">Growflowlla on oikeus rajoittaa tai estää sellainen Palvelun käyttö sekä poistaa sellainen materiaali, joka loukkaa lakia, hyvää tapaa tai kolmannen suojattuja oikeuksia, tai joka kohtuuttomasti kuormittaa Palvelua tai verkkoa, uhkaa tietoturvaa tai tietosuojaa, haittaa Palvelun käyttäjiä, muita kolmansia tai Growflowa taikka on muutoin Käyttöehtojen, Erityisehtojen tai muiden soveltuvien sääntöjen, kuten Palvelun tilausehtojen, vastaista.</p>
                                <p class="pb-3 body-text">Growflowlla on oikeus luovuttaa Asiakkaan henkilötiedot viranomaiselle viranomaisen tai tuomioistuimen määräyksestä siinä tapauksessa, että on perusteltu syy epäillä, että Asiakkaan toiminta täyttää rikoksen tunnusmerkistön.</p>
                                <p class="pb-3 body-text">Growflow voi tarpeelliseksi katsoessaan asiasta ennalta ilmoittamatta myös estää Asiakkaan pääsyn Palveluun ja/tai Palvelun vastaanoton, esimerkiksi jos se on tarpeen verkon tai Palvelun kehittämiseksi tai muuttamiseksi, puutteellisuuksien ja vikojen korjaamiseksi, tai muista huolto- tai ylläpitotöistä taikka laista, viranomaisen määräyksistä tai muista vastaavista syistä johtuen. Muista kuin äkillisistä tai vähäisistä keskeytyksistä Growflow pyrkii ilmoittamaan asiakkaalle etukäteen parhaaksi katsomallaan tavalla, esimerkiksi Palvelussa.</p>
                                <p class="pb-3 body-text">Käyttöoikeuden tai tilauksen päättymisestä huolimatta jäävät voimaan Käyttöehtoihin ja Erityisehtoihin perustuvat osapuolten oikeudet ja velvollisuudet, jotka ovat merkityksellisiä päättymisen jälkeen (esim. oikeus vahingonkorvaukseen ja omistus- ja tekijänoikeudet).</p>
                                <h3 id="21-palvelun-toimittaminen" class="heading-lg pb-3 pt-6">2.1. Palvelun toimittaminen</h3>
                                <p class="pb-3 body-text">Palvelu on Asiakkaan käytettävissä lähtökohtaisesti 24 tuntia vuorokaudessa. Palvelun virheettömyyttä tai keskeytyksetöntä toimivuutta ei taata. Growflow tai sen sopimuskumppanit eivät missään olosuhteissa vastaa mahdollisista vahingoista, jotka aiheutuvat käytettävälle tietokonejärjestelmälle tai siinä oleville tiedoille mukaan lukien tietoturvallisuusriskit (virukset, tietovarkaudet yms.).</p>
                                <p class="pb-3 body-text">Growflow toimittaa Palvelun Asiakkaalle parhaaksi katsomallaan tavalla. Palvelussa on virhe, jos se olennaisesti poikkeaa määritellyistä tai muutoin sovituista ominaisuuksista ja tämä poikkeama estää olennaisella tavalla Palvelun käytön. Palvelut tarjotaan Asiakkaalle ”sellaisena kuin ne ovat” eikä Growflow anna mitään suoranaisia tai välillisiä takuita Palvelun toiminnasta tai piirteistä eikä Growflow takaa, että Palvelu toimii käyttökatkoitta ja virheettömästi</p>
                                <p class="pb-3 body-text">Palvelu on suunnattu yksinomaan Suomeen, ellei erikseen ole nimenomaisesti muuta sovittu tai ilmoitettu.</p>
                                <h3 id="22-kayttkatkot" class="heading-lg pb-3 pt-6">2.2. Käyttökatkot</h3>
                                <p class="pb-3 body-text">Palvelun käyttökatkot ovat mahdollisia huollon, liiallisen kuormituksen tai muun syyn vuoksi. Growflow pyrkii informoimaan Asiakasta käyttökatkoista. Growflow ei vastaa mahdollisista käyttökatkojen aiheuttamista katoamisista tai keskeytyksistä Palveluun tai sen osaan. Mikäli Palvelun tarjoaminen keskeytyy Growflowsta johtuvasta syystä yli vuorokauden ajaksi, Asiakkaan tulee reklamoida keskeytyksestä asiakaspalveluun.</p>
                                <h3 id="23-kayttajatunnukset" class="heading-lg pb-3 pt-6">2.3. Käyttäjätunnukset</h3>
                                <p class="pb-3 body-text">Palvelun käyttäjätunnukset ovat asiakaskohtaisia. Käyttäjätunnuksia ei saa luovuttaa tai ilmaista oikeudettomasti muille. Asiakas on vastuussa käyttäjätunnuksiensa käytöstä sekä kaikista kustannuksista ja vahingoista joita niiden väärinkäytöstä aiheutuu. Growflowlla on oikeus rajoittaa käyttäjätunnusten käyttöä ja sulkea pääsy Palveluun väärinkäyttötapauksissa.</p>
                                <p class="pb-3 body-text">Asiakkaan tulee ilmoittaa välittömästi Growflowlle käyttäjätunnustensa katoamisesta tai paljastumisesta ulkopuoliselle. Ilmoitus tulee tehdä sähköpostilla osoitteeseen
                                    <a href="mailto:tietosuojapyynnot@Growflow.com" class="link underline">tietosuojapyynnot@Growflow.com</a>
                                    . Asiakas vastaa käyttäjätunnustensa käytöstä, kunnes hän on tehnyt ilmoituksen ja Growflow on kuitannut vastaanottaneensa sen.
                                </p>
                                <p class="pb-3 body-text">Growflow seuraa käyttäjätunnusten käyttöä ja voi lähettää Asiakkaalle huomautuksen, mikäli on perusteltu syy epäillä, että käyttäjätunnuksia on käytetty ehtojen vastaisesti. Growflow voi vaatia Asiakkaalta myös käyttäjätunnusten käyttämiseen liittyvää selvitystä väärinkäytösten ehkäisemiseksi, Asiakkaan tietoturvan varmistamiseksi ja edellä mainittujen rajoitusten poistamiseksi. Selvitys toimitetaan Growflowlle sähköpostilla osoitteeseen
                                    <a href="mailto:tietosuojapyynnot@Growflow.com" class="link underline">tietosuojapyynnot@Growflow.com</a>
                                    tai muulla erikseen ilmoitetulla tavalla.
                                </p>
                                <p class="pb-3 body-text">Palvelun käyttö voi edellyttää voimassa olevaa tilausta ja/tai siihen liittyvää Growflow-tiliä. Maksullisten palveluiden osalta, käyttöön voi liittyä lisäksi tilausehdoissa määriteltyjä rajoituksia. Esimerkiksi käyttäjätunnusten päällekkäinen käyttö useilla päätelaitteilla voi olla rajoitettua.</p>
                                <p class="pb-3 body-text">Organisaation käyttöoikeus Palveluun perustuu organisaation Growflowlle ilmoittamaan käyttäjämäärään. Organisaatio on velvollinen ilmoittamaan etukäteen Growflowlle sekä sopimaan laajemmasta käyttöoikeudesta, mikäli sovittu käyttäjämäärä ylittyy.</p>
                                <h3 id="24-asiakkaan-antamat-tiedot" class="heading-lg pb-3 pt-6">2.4. Asiakkaan antamat tiedot</h3>
                                <p class="pb-3 body-text">Asiakkaan tulee antaa Growflowlle pyydetyt Palvelua tai sen toteuttamista varten tarvittavat tiedot. Asiakas vakuuttaa ilmoittaneensa tiedot oikein ja ajantasaisina. Asiakkaan tulee viivytyksettä ilmoittaa tietojensa muutoksista. Asiakkaan ilmoittamia yhteystietoja voidaan käyttää myös tämän tunnistamiseen salasanaa vaihdettaessa. Asiakas vastaa virheistä tai viivästyksistä, jotka johtuvat siitä, että hänen antamansa tiedot ovat puutteellisia tai vanhentuneita.</p>
                                <h3 id="25-muiden-palveluntarjoajien-palveluiden-ehdot" class="heading-lg pb-3 pt-6">2.5. Muiden palveluntarjoajien palveluiden ehdot</h3>
                                <p class="pb-3 body-text">Palveluihin jotka on saatettu Asiakkaan saataville Applen AppStoren, Google Playn tai muun palveluntarjoajan kautta, sovelletaan lisäksi myös kyseisen palveluntarjoajan käyttöehtoja ja tietosuojalauseketta.</p>
                                <p class="pb-3 body-text">Palvelu saattaa sisältää linkkejä ja yhteyksiä kolmannen osapuolen verkkosivustoihin. Tällaisiin kolmannen osapuolen tarjoamiin palveluihin sovelletaan kyseisen kolmannen osapuolen käyttö- ja muita ehtoja, eikä Growflow vastaa näiden sivustojen tietosuojakäytännöistä tai sisällöstä</p>
                                <h3 id="26-palkinnot" class="heading-lg pb-3 pt-6">2.6. Palkinnot</h3>
                                <p class="pb-3 body-text">Palvelun yhteydessä voi olla mahdollista voittaa taitoon perustuvissa kilpailuissa ja sattumaan perustuvissa arvonnoissa erilaisia Growflown tai sen yhteistyökumppanien ja sponsorien kulloinkin tarjoamia palkintoja. Palkinnot myöntää joko Growflow tai Palvelun yhteydessä ilmoitettu yhteistyökumppani tai sponsori. Palkinnon voittajille ilmoitetaan voitosta henkilökohtaisesti.</p>
                                <p class="pb-3 body-text">Arvonnan järjestäjät vastaavat arpajaisverosta. Kilpailusta saatu palkinto katsotaan palkinnon saajan veronalaiseksi tuloksi ja palkinnon antajan sekä Asiakkaan tulee ilmoittaa se verottajalle. Growflow ei miltään osin vastaa kolmannen osapuolen (kuten Palvelun yhteistyökumppanin) myöntämistä palkinnoista, palkintojen saatavuudesta, toimivuudesta, niiden käytöstä aiheutuvista vahingoista tai muista palkintoihin liittyvistä kuluista.</p>
                                <p class="pb-3 body-text">Palkinnon saamisen edellytyksenä voi olla, että palkinnon saaja ilmoittaa Palvelun tarjoajalle tai palkinnon myöntävälle yhteistyökumppanille palkinnosta tehtävää veroilmoitusta varten tarvittavat henkilötiedot. Palkintoa ei voi muuttaa rahaksi.</p>
                                <p class="pb-3 body-text">Palkinnon antaja varaa oikeuden muuttaa palkintoja ajankohdasta riippumatta, ilmoittamalla asiasta etukäteen Palvelun yhteydessä.</p>
                                <h2 id="3-palvelun-ja-omistus--ja-tekijanoikeudet" class="heading-xl hyphenate pb-3 pt-6">3. Palvelun ja omistus- ja tekijänoikeudet</h2>
                                <h3 id="31-Growflown-oikeudet" class="heading-lg pb-3 pt-6">3.1. Growflown oikeudet</h3>
                                <p class="pb-3 body-text">Palvelun sisältö ja ulkoasu (”Sisältö”) on suojattu tekijänoikeuksin Suomen lainsäädännön ja kansainvälisten sopimusten mukaisesti. Palvelun kaikki omistusoikeudet (mukaan lukien tekijän-, tavaramerkki- ja muut immateriaalioikeudet) ovat Growflowlla, sen sopimuskumppaneilla tai muilla Palveluun tietoa tuottavilla tahoilla. Growflow pidättää itsellään kaikki oikeudet Sisältöön, ellei toisin ole mainittu.</p>
                                <p class="pb-3 body-text">Asiakkaalla ei ole oikeutta julkisesti käyttää taikka taltioida, edelleen lähettää tai muutoin hyödyntää Palvelua Growflown tai sen sopimuskumppanien oikeuksia loukaten.</p>
                                <p class="pb-3 body-text">Sisällön tai sen osan saattaminen yleisön saataviin välittämällä, levittämällä, esittämällä tai näyttämällä julkisesti sekä varastointi tai kappaleiden valmistaminen Sisällöstä tai sen osasta ilman Growflown etukäteen antamaa nimenomaista suostumusta on kielletty. Asiakkaalla ei ole oikeutta Palvelun tai sen osan julkaisemiseen tai edelleen luovuttamiseen. Kielto koskee sekä vastikkeellisia että vastikkeettomia luovutuksia sekä tilanteita, joissa Palvelu saatetaan kolmansien saataville. Asiakkaalla ei ole oikeutta muodostaa Palvelusta tai sen osasta toista teosta tai toista palvelua.</p>
                                <p class="pb-3 body-text">Asiakkaalla ei ole oikeutta ilman Growflown etukäteen antamaa nimenomaista kirjallista suostumusta käyttää automaattisia järjestelmiä (mukaan lukien ”robot-”, ”spider-” ”scraper-” ja ”offline reader-” ohjelmistot) kappaleiden valmistamiseksi Palvelusta, Sisällöstä tai niiden osista, tai niiden saattamiseksi yleisön saataviin.</p>
                                <p class="pb-3 body-text">Mahdollisen kopiosuojauksen kiertäminen tai sen yritys on kielletty.</p>
                                <p class="pb-3 body-text">Asiakkaalla on oikeus hyödyntää Palvelua ja sen osia yksityiseen käyttöön.</p>
                                <h3 id="32-asiakkaan-toimittama-materiaali" class="heading-lg pb-3 pt-6">3.2. Asiakkaan toimittama materiaali</h3>
                                <p class="pb-3 body-text">Growflowlla on oikeus korvauksetta käyttää ja uudelleen julkaista tai luovuttaa edelleen muunneltuna tai alkuperäisessä asussaan joko kokonaan tai osittain ja/tai liitettynä johonkin toiseen aineistoon Asiakkaan Palveluun toimittamaa tai Palvelun julkisille alueille (kuten keskustelufoorumit) tai muutoin Growflown käyttöön lähettämää tai välittämää materiaalia (esimerkiksi kuva-, video- ja tekstimateriaali) pois lukien Asiakkaan Growflowlle rekisteröitymisen yhteydessä antamat henkilötiedot. Growflown liike-, tiedonvälitys-, pr-, tai muussa toiminnassa. Growflowlla on omassa harkinnassaan oikeus olla julkaisematta Asiakkaan toimittamaa materiaalia sekä poistaa Palvelusta jo julkaistu materiaali.</p>
                                <p class="pb-3 body-text">Mikäli Asiakas toimittaa Palveluun kuva-, video- tai muuta materiaalia, vastaa hän samalla siitä, että hänellä on kaikki tarvittavat tekijän- ja muut oikeudet siihen. Tämä tarkoittaa sitä, että Asiakas on itse kuvannut tai muutoin luonut lähettämänsä materiaalin, taikka että materiaalin kuvannut tai materiaalin luomiseen muutoin osallistuneet henkilöt ovat luovuttaneet Asiakkaalle kaikki tarvittavat tekijänoikeutensa (mukaan lukien muuntelu- ja edelleenluovutusoikeuden), ja että materiaalin tallentamiseen on ollut lupa.</p>
                                <p class="pb-3 body-text">Asiakkaalla tulee olla tarvittavat suostumukset kaikilta materiaalissa esiintyviltä henkilöiltä siihen, että Growflow ja/tai Growflown yhteistyökumppanit voivat hyödyntää ja käsitellä materiaalia parhaaksi katsomallaan tai erikseen sovitulla tavalla, kuten kaupallisesti tai uutistarkoituksessa. Materiaalin lähettäneen Asiakkaan tulee kysyttäessä pystyä esittämään kyseiset suostumukset. Alaikäisten osalta tulee tarvittaessa voida esittää huoltajan suostumus. Asiakas vakuuttaa myös, että hän ei ole luovuttanut tai tule luovuttamaan materiaalia yksinoikeudella millekään kolmannelle taholle.</p>
                                <p class="pb-3 body-text">Lähettämällä materiaalia Asiakas hyväksyy ja vahvistaa, että materiaali ei ole loukkaavaa, uhkaavaa, siveetöntä, halventavaa tai laitonta.</p>
                                <p class="pb-3 body-text">Growflow ei vastaa Asiakkaan näiden Käyttöehtojen tai Erityisehtojen vastaisesti lähettämästä materiaalista tai siihen liittyvistä tekijänoikeuksista ja muista immateriaalioikeuksista.</p>
                                <h3 id="33-sallittu-ja-kielletty-linkitys-palveluun" class="heading-lg pb-3 pt-6">3.3. Sallittu ja kielletty linkitys Palveluun</h3>
                                <p class="pb-3 body-text">Asiakkaalla on hyvän tavan mukaisesti oikeus sijoittaa omille verkkosivuilleen linkki Palvelun pääsivulle, ellei Palvelun Erityisehdoissa tai muutoin Palvelun yhteydessä ole toisin todettu. Muunlainen linkittäminen voi myös erikseen olla mahdollistettu tai sallittu muilla tavoin itse Palvelussa.</p>
                                <p class="pb-3 body-text">Hyvä tapa muun muassa edellyttää, ettei linkittäminen tapahdu sopimattomassa tai loukkaavassa yhteydessä, ja ettei linkittäminen luo virheellistä käsitystä Growflown ja linkittäjän tai muun tahon suhteesta taikka loukkaa Growflown immateriaalioikeuksia.</p>
                                <p class="pb-3 body-text">Linkitetyn sivuston on auettava tyhjään ikkunaan ilman kehyksiä. Muu linkitys kaupallisessa tai taloudellisessa tarkoituksessa, esimerkiksi osaksi kaupallista sisältöpalvelua taikka tietokannan tai uuden palvelun tuottamiseksi on kielletty ilman Growflown etukäteen antamaa nimenomaista kirjallista suostumusta.</p>
                                <p class="pb-3 body-text">Growflowlla on oikeus peruuttaa suostumuksensa linkitykseen koska tahansa, sekä kieltää linkitys, joka voi aiheuttaa haittaa Growflown liiketoiminnalle tai maineelle.</p>
                                <h2 id="4-kommentointi-ja-kayttajien-valinen-toiminta" class="heading-xl hyphenate pb-3 pt-6">4. Kommentointi ja käyttäjien välinen toiminta</h2>
                                <p class="pb-3 body-text">Palveluissa voi tapahtua Asiakkaan ja muiden käyttäjien välistä viestintää joko suoraan yksityisviestien ja keskustelufoorumeiden kautta tai epäsuorasti Palveluun jätetyn sisällön kautta. Growflow ei vastaa käyttäjien välisen viestinnän tai muun toiminnan toisille käyttäjille tai kolmannelle taholle mahdollisesti aiheuttamista haitoista tai vahingoista.</p>
                                <p class="pb-3 body-text">Palvelussa olevaan toimitukselliseen sisältöön voi liittyä kommentointiosio, jossa julkaistavat kirjoitukset valitsee kyseisestä sisällöstä vastaavan julkaisun toimitus. Kommentoinnissa julkaistavat kirjoitukset mielipiteet eivät välttämättä edusta kyseisen julkaisun, sen toimituksen tai Growflown mielipiteitä tai linjaa.</p>
                                <p class="pb-3 body-text">Kirjoittaja myöntää Growflowlle oikeuden muokata, poistaa, kopioida, julkaista tai olla julkaisematta kokonaan tai osittain sellaista aineistoa, jonka kirjoittaja on lähettänyt kommentointiosioon.</p>
                                <p class="pb-3 body-text">Kommentointiosiossa julkaistavien tekstien kirjoittajien henkilöllisyys ja yhteystiedot ovat lähtökohtaisesti luottamuksellisia tietoja, ellei Asiakkaalle ole ilmoitettu toisin. Growflowlla on kuitenkin harkintansa mukaan oikeus luovuttaa Asiakkaan nimi- ja yhteystiedot poliisi- tai muulle viranomaiselle. Tiedot voidaan luovuttaa, jos on syytä epäillä, että itse kirjoituksella on syyllistytty rikolliseen tekoon tai että on tapahtunut rikos, jonka selvittämistä voidaan edistää Asiakkaan nimi- ja yhteystiedot luovuttamalla ja viranomainen esittää tätä koskevan perustellun pyynnön.</p>
                                <p class="pb-3 body-text">Kommentointiosioon toimitetun aineiston kirjoittaja vastaa siitä, että hänen tekstinsä on lakien ja hyvien tapojen mukaista. Kirjoittaja on Suomen lain mukaisesti rikos- ja vahingonkorvausoikeudellisessa vastuussa kirjoitustensa sisällöstä.</p>
                                <h2 id="5-ehtojen-ja-palvelun-muuttaminen" class="heading-xl hyphenate pb-3 pt-6">5. Ehtojen ja Palvelun muuttaminen</h2>
                                <h3 id="51-ehtojen-muuttaminen" class="heading-lg pb-3 pt-6">5.1. Ehtojen muuttaminen</h3>
                                <p class="pb-3 body-text">Growflowlla on oikeus tehdä ehtoihinsa vapaasti sellaisia muutoksia, jotka eivät koidu Asiakkaan vahingoksi.</p>
                                <p class="pb-3 body-text">Muussa tapauksessa Growflow varaa oikeuden muuttaa Palvelun käyttöä koskevia Käyttöehtoja, Erityisehtoja, sekä Palveluiden hintoja ja laskutusperustetta oman harkintansa mukaan ilmoittamalla siitä sopivaksi katsotulla tavalla hyvissä ajoin etukäteen.</p>
                                <p class="pb-3 body-text">Laista, asetuksista tai viranomaisten toimenpiteistä aiheutuvat hintojen tai ehtojen muutokset tulevat kuitenkin voimaan määräysten voimaantulosta lukien ilman eri ilmoitusta. Lisäksi, jos arvonlisävero tai jokin muu soveltuva vero tai julkinen maksu tai niitä koskeva viranomaisten soveltamiskäytäntö muuttuu, Growflowlla on oikeus välittömästi muuttaa hintoja vastaavasti.</p>
                                <p class="pb-3 body-text">Ehtojen muutoksista ilmoitetaan Palvelussa tai muulla vastaavalla tavalla. Ellei muuta ole ilmoitettu, astuvat muutokset voimaan välittömästi. Jatkamalla Palvelun käyttöä sitoutuu Asiakas noudattamaan muutettuja ehtoja.</p>
                                <h3 id="52-palvelun-muuttaminen" class="heading-lg pb-3 pt-6">5.2. Palvelun muuttaminen</h3>
                                <p class="pb-3 body-text">Growflow pyrkii kehittämään Palveluita ja huolehtimaan niiden mahdollisimman häiriöttömästä toiminnasta. Growflowlla on oikeus lisätä, muuttaa tai poistaa Palvelun tai niiden osien sisältöä, rakennetta, palveluaikoja, tai muita niihin liittyviä seikkoja sekä muuttaa maksuttomia osioita maksullisiksi. Growflowlla on perustellusta syystä oikeus lopettaa Palvelun tarjoaminen osittain tai kokonaan.</p>
                                <p class="pb-3 body-text">Mikäli Growflow lopettaa maksullisen Palvelun tarjoamisen sen ostaneelle Asiakkaalle, sitoutuu se palauttamaan Asiakkaalle määrän, joka vastaa tämän jäljellä olevaa Palveluun kohdistuvaa käyttöoikeutta. Määrä palautetaan edellyttäen, että se ylittää viisi (5) euroa ja, että Asiakas ilmoittaa Growflowlle määrän palauttamiseen tarvittavat pankkiyhteystiedot ja/tai luottokorttitiedot.</p>
                                <p class="pb-3 body-text">Jos muutokset edellyttävät muutoksia Asiakkaan laitteisiin tai ohjelmistoihin tai muita toimenpiteitä Asiakkaan toimesta, Growflow pyrkii ilmoittamaan muutoksista hyvissä ajoin etukäteen. Asiakas vastaa omalla kustannuksellaan laitteisiinsa ja ohjelmistoihinsa tarvittavista muutoksista.</p>
                                <h2 id="6-vastuu-ja-vahingonkorvaus" class="heading-xl hyphenate pb-3 pt-6">6. Vastuu ja vahingonkorvaus</h2>
                                <h3 id="61-Growflown-vastuusta" class="heading-lg pb-3 pt-6">6.1. Growflown vastuusta</h3>
                                <p class="pb-3 body-text">Growflow on vastuussa Asiakkaalle Growflown tuottamuksesta aiheutuneista, Asiakkaan osoittamista välittömistä vahingoista. Growflow on korvausvelvollinen vain siltä osin kuin Asiakkaan kärsimä vahinko ylittää näiden Käyttöehtojen tai Erityisehtojen mukaisesti Asiakkaalle mahdollisesti annetun hyvityksen.</p>
                                <p class="pb-3 body-text">Growflow ei missään tapauksessa vastaa Asiakkaalle Palvelusta tai muusta syystä mahdollisesti aiheutuvista välillisistä vahingoista, kuten saamatta jääneestä voitosta, tuotantotappiosta, tiedon ja tulojen menetyksestä, toiminnan keskeytyksistä ja niistä aiheutuneista tappioista. Selvyyden vuoksi todetaan, että Growflow ei ole vastuussa tai korvausvelvollinen Asiakkaalle Palvelun virheellisestä toiminnasta, käyttökatkoista, käytön estymisestä, Palvelussa olevista virheistä, puutteellisuuksista, tai Palvelun tai sen osan lopettamisesta mahdollisesti aiheutuvasta vahingosta eikä Asiakkaan laitteisiin tai ohjelmistoihin tulevista vioista tai häiriöistä.</p>
                                <p class="pb-3 body-text">Growflow vastaa Palveluun itse tuottamansa sisällön lainmukaisuudesta. Growflow ei muutoin vastaa Palvelun kautta tai avulla toimitettavasta tai saatavasta sisällöstä tai sen luotettavuudesta. Palveluun sisältyvät tiedot annetaan "sellaisina kuin ne ovat" ilman minkäänlaisia takuita Palvelun sisältämän informaaation käyttö tapahtuu Asiakkaan omalla vastuulla, eikä Growflow vastaa Palvelun sisällön perusteella tapahtuvasta Asiakkaan toiminnasta.</p>
                                <p class="pb-3 body-text">Growflow ei myöskään vastaa toisen palveluntarjoajan palvelusta tai sen sisällöstä, taikka niihin liittyvistä tekijänoikeuksista ja muista immateriaalioikeuksista miltään osin silloinkaan, kun näihin pääsee Growflown Palvelun kautta linkillä tai muulla tavoin.</p>
                                <p class="pb-3 body-text">Vahingonkorvausta on vaadittava Growflowlta kahden kuukauden kuluessa siitä, kun Asiakas havaitsi tai tämän olisi pitänyt havaita vahingonkorvauksen peruste. Maksullisten Palveluiden osalta Growflown vastuu kaikista vahingoista rajoittuu Asiakkaan vahingon kohteena olevasta Maksullisesta Palvelusta tai tuotteesta vahingon ajalta maksaman maksun määrään</p>
                                <h3 id="62-asiakkaan-vastuusta" class="heading-lg pb-3 pt-6">6.2. Asiakkaan vastuusta</h3>
                                <p class="pb-3 body-text">Asiakas vastaa itse Palvelun käytöstä sekä Palveluun jättämästään tai niiden kautta muille käyttäjille ja muihin tietoverkkoihin jakamastaan materiaalista ja siitä, ettei käyttö tai edellä mainittu materiaali loukkaa kolmannen tekijän-, teollis- ja muita suojattuja oikeuksista tai ole Käyttöehtojen, Erityisehtojen, lain tai hyvän tavan vastaista tai aiheuta haittaa tai häiriötä verkolle, Growflowlle, Growflown sopimuskumppaneille, Palvelun muille käyttäjille tai muille kolmansille osapuolille.</p>
                                <p class="pb-3 body-text">Asiakas vastaa soveltuvan lainsäädännön ja muiden säädösten, Käyttöehtojen sekä hyvän tavan vastaisesta toiminnastaan ja sitoutuu korvaamaan Growflowlle tai kolmannelle aiheuttamansa vahingon.</p>
                                <h2 id="7-tietosuoja" class="heading-xl hyphenate pb-3 pt-6">7. Tietosuoja</h2>
                                <h3 id="71-henkiltietojen-kaytt" class="heading-lg pb-3 pt-6">7.1. Henkilötietojen käyttö</h3>
                                <p class="pb-3 body-text">Growflow käsittelee Asiakkaan henkilötietoja Growflown tietosuojalausekkeen sekä tietosuojaa koskevan lainsäädännön mukaisesti. Tietosuojalausekkeen lisäksi Palveluilla voi olla palvelukohtaisia kuvauksia henkilötietojen käsittelystä.</p>
                                <p class="pb-3 body-text">Growflow käsittelee henkilötietoja muun muassa. Palvelun toimittamista, asiakasviestintää ja -palvelua, Palvelun personointia, tuotekehitystä, kävijämittausta sekä mainonnan ja markkinoinnin kohdentamista varten.</p>
                                <p class="pb-3 body-text">Growflow voi lähettää Asiakkaalle asiakkuuteen perustuvia, samankaltaisiin tuotteisiin liittyviä sähköisiä markkinointiviestejä. Asiakas voi kieltää viestien lähettämisen viestissä olevan linkin kautta.</p>
                                <p class="pb-3 body-text">Asiakkaan tai asiakaspalveluun yhteyttä ottaneen henkilön ja Growflown väliset puhelut sekä puhelinmyynnin soittamat myyntipuhelut tallennetaan asioinnin varmentamiseksi sekä laadun ja osaamisen kehittämistä varten.</p>
                                <p class="pb-3 body-text">Henkilötietojen käsittelyä on kuvattu tarkemmin
                                    <a href="https://Growflow.fi/tietoa-meista/tietosuoja/tietosuojalauseke/" class="link underline">Growflown tietosuojalausekkeessa.</a>
                                </p>
                                <h3 id="72-evasteet" class="heading-lg pb-3 pt-6">7.2. Evästeet</h3>
                                <p class="pb-3 body-text">Palveluissa käytetään evästeitä ja muita tekniikoita
                                    <a href="https://Growflow.fi/tietoa-meista/tietosuoja/evastekaytannot/" class="link underline">Growflown evästekäytännöissä</a>
                                    kuvatuin tavoin.
                                </p>
                                <p class="pb-3 body-text">Growflow käyttää evästeitä muun muassa Palveluiden toiminnallisuuksien mahdollistamiseen, kävijämäärien tilastolliseen seurantaan, käyttäjäkyselyiden tai sivuston käytettävyyden testaamiseen ja analysointiin sekä mainonnan tehon mittaamiseen ja kohdentamiseen.</p>
                                <h2 id="8-muut-ehdot" class="heading-xl hyphenate pb-3 pt-6">8. Muut ehdot</h2>
                                <h3 id="81-sopimuksen-siirtaminen" class="heading-lg pb-3 pt-6">8.1. Sopimuksen siirtäminen</h3>
                                <p class="pb-3 body-text">Palvelun käyttöoikeuden siirtäminen on kielletty ilman Growflown etukäteen antamaa kirjallista lupaa.</p>
                                <p class="pb-3 body-text">Growflowlla on oikeus siirtää Palvelu ja sen ylläpitäminen sekä siihen liittyvät asiakkuudet ja henkilörekisterit Growflow-konserniin kulloinkin kuuluvalle yhtiölle sekä liiketoiminnan kaupan yhteydessä liiketoiminnan vastaanottavalle taholle.</p>
                                <h3 id="82-ylivoimainen-este" class="heading-lg pb-3 pt-6">8.2. Ylivoimainen este</h3>
                                <p class="pb-3 body-text">Palveluun ja näihin Käyttöehtoihin, sekä Erityisehtoihin sovelletaan Suomen lakia, pois lukien lainvalintaa koskevat säännökset. Growflown ja Asiakkaan väliset mahdolliset erimielisyydet pyritään ratkaisemaan osapuolten välisillä neuvotteluilla. Mikäli osapuolet eivät kuitenkaan pääse sovintoon, ratkaistaan asia Helsingin käräjäoikeudessa. Asiakas voi nostaa kanteen myös sen paikkakunnan alioikeudessa, jonka tuomiopiirissä hänellä on kotipaikka.</p>
                                <p class="pb-3 body-text">Mikäli riitakysymys kuitenkin koskee sekä markkinaoikeuden toimivaltaan kuuluvaa asiaa (esimerkiksi immateriaalioikeuksien loukkaus) että näihin Käyttöehtoihin liittyvää asiaa, riita ratkaistaan markkinaoikeudessa.</p>
                                <p class="pb-3 body-text">Kuluttajan on myös mahdollista saattaa riita-asia
                                    <a href="http://www.kuluttajariita.fi/" class="link underline">kuluttajariitalautakunnan</a>
                                    käsiteltäväksi. Ennen asian viemistä kuluttajariitalautakuntaan, kuluttajan tulee olla yhteydessä
                                    <a href="http://www.kuluttajaneuvonta.fi/" class="link underline">kuluttajaneuvontaan</a>
                                    . Euroopan komissio tarjoaa myös
                                    <a href="http://ec.europa.eu/consumers/odr/" class="link underline">verkkovälitteisen riidanratkaisufoorumin</a>
                                    , joka on erityisesti tarkoitettu toisessa EU-maassa asuvalle kuluttajalle.
                                </p>
                                <h3 id="83-kuluttajasuoja-ja-muu-lainsaadant" class="heading-lg pb-3 pt-6">8.3. Kuluttajasuoja ja muu lainsäädäntö</h3>
                                <p class="pb-3 body-text">Näillä ehdoilla ei rajoiteta Asiakkaalle pakottavasta kuluttajalainsäädännöstä tai muusta pakottavasta lainsäädännöstä seuraavia oikeuksia.</p>
                                <h2 id="9-yhteystiedot" class="heading-xl hyphenate pb-3 pt-6">9. Yhteystiedot</h2>
                                <p class="pb-3 body-text">Palveluiden yhteystiedot löydät
                                    <a href="https://oma.Growflow.fi/yhteystiedot" class="link underline">täältä</a>
                                    .
                                </p>
                                <h2 id="10-ehtojen-voimassaolo" class="heading-xl hyphenate pb-3 pt-6">10. Ehtojen voimassaolo</h2>
                                <p class="pb-3 body-text">Nämä ehdot tulevat voimaan 23.4.2021 ja ovat voimassa toistaiseksi</p>
                            </div>

                        </div>
                    </div>
                </section>

            </div>
        );
    }
}

export default TermsAndConditionsPage;